server:
  port: ${PORT:8081}
  tomcat:
    threads:
      max: 500        # Mở rộng trần luồng xử lý để gánh bão 500 users (Mặc định chỉ có 200)
      min-spare: 50   # Luôn giữ sẵn 50 luồng chờ sẵn để phản xạ nhanh với bão tải
    accept-count: 50 

spring:
  application:
    name: REGISTRATION-SERVICE-ALB

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${PORT:8081}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics" 
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      jvm: false    
      tomcat: false 
  observations:
    http:
      server:
        requests:
          enabled: true