name: CI/CD Auto Deploy to Ubuntu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Action chuẩn của GitHub tự động xử lý xác thực (Auth) và tải code mới nhất về
      - name: Checkout source code
        uses: actions/checkout@v4

      # Build và khởi chạy Docker trực tiếp tại không gian làm việc của Runner
      - name: Build and deploy
        run: |
          docker compose build
          docker compose up -d