name: CI/CD Auto Deploy to Ubuntu

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-production
  cancel-in-progress: true   # Tự hủy job cũ khi có job mới

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          docker compose config
          docker compose down
          docker compose build --no-cache
          docker compose up -d